import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Card, Space, Alert, Form, Input, Button } from "antd";
import { useState } from "react";
import axios from "axios";
import { FilesUploadQueuesResponsePayload } from "@/pages/api/parser/files/getUploadQueues";
import { ParserResponsePayload } from "@/pages/api/parser/parse";
import { Nullable } from "@/utils/types";
import { FileToCDNUpload } from "@/utils/getFilesUploadQueues";

export type ParserFormFields = {
  url: string;
  containerSelector: string;
};

export default function Home() {
  const [form] = Form.useForm<ParserFormFields>();
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [isEnd, setIsEnd] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<Nullable<string>>(null);
  const [successMessage, setSuccessMessage] = useState<Nullable<string>>(null);
  const [loadingButtonText, setLoadingButtonText] = useState<string>(``);
  const [resultFolderTimestamp, setResultFolderTimestamp] =
    useState<Nullable<string>>(null);

  const fetchFilesUploadQueues =
    async (): Promise<FilesUploadQueuesResponsePayload | void> => {
      try {
        const { data } = await axios.get<FilesUploadQueuesResponsePayload>(
          `/api/parser/files/getUploadQueues`
        );

        return data;
      } catch (err) {
        if (axios.isAxiosError(err)) {
          setErrorMessage(err.message);
        } else {
          console.log("unexpected err: ", err);
          setErrorMessage(`🦜 Неожиданная ошибка! Позвать разраба на мостик!`);
        }
        setIsLoading(false);
      }
    };

  const fetchParseRichContent = async ({
    url,
    containerSelector,
  }: ParserFormFields): Promise<ParserResponsePayload | void> => {
    try {
      const { data } = await axios.get<ParserResponsePayload>(
        `/api/parser/parse?url=${url}&containerSelector=${containerSelector}`
      );

      return data;
    } catch (err) {
      if (axios.isAxiosError(err)) {
        setErrorMessage(err.message);
      } else {
        console.log("unexpected err: ", err);
        setErrorMessage(`🦜 Неожиданная ошибка! Позвать разраба на мостик!`);
      }
      setIsLoading(false);
    }
  };

  const fetchUploadParsedFilesToCDN = async (
    filesToUpload: FileToCDNUpload[]
  ): Promise<void> => {
    try {
      await axios.get<void>(
        `/api/parser/files/cdnUpload?files=${JSON.stringify(filesToUpload)}`
      );
    } catch (err) {
      if (axios.isAxiosError(err)) {
        setErrorMessage(err.message);
      } else {
        console.log("unexpected err: ", err);
        setErrorMessage(`🦜 Неожиданная ошибка! Позвать разраба на мостик!`);
      }
      setIsLoading(false);
    }
  };

  const onSubmit = async (formFields: ParserFormFields) => {
    setErrorMessage(null);
    setSuccessMessage(null);
    setIsEnd(false);
    setIsLoading(true);
    setResultFolderTimestamp(null);
    setLoadingButtonText(`Паршу вёрстку и изображения...`);

    const parserResponse = await fetchParseRichContent(formFields);
    if (!parserResponse) return;

    if (parserResponse.err) {
      setErrorMessage(parserResponse.err);
      return;
    }

    if (parserResponse && parserResponse.timestamp) {
      setLoadingButtonText(`Подготавливаю файлы для загрузки на CDN...`);
      setResultFolderTimestamp(parserResponse.timestamp);

      const res = await fetchFilesUploadQueues();

      if (!res) return;

      if (res.err) {
        setErrorMessage(res.err);
        return;
      }

      setLoadingButtonText(`Загружаю файлы на CDN...`);

      for await (const filesToUpload of res.filesUploadQueues) {
        await fetchUploadParsedFilesToCDN(filesToUpload);
      }

      setTimeout(() => {
        setIsEnd(true);
        setSuccessMessage(`🦜 Абордаж успешен! Что дальше, капитан?`);
        setIsLoading(false);
        setLoadingButtonText(``);
      }, 5000);
    }
  };

  return (
    <>
      <Head>
        <title>🏴‍☠️ Yo-ho-ho!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Card
          title="🏴‍☠️ Rich Content Pirate v0.9.0-beta"
          style={{ width: "40rem" }}
        >
          <Form form={form} onFinish={onSubmit} layout="vertical">
            <Space direction="vertical" size={20} style={{ width: "100%" }}>
              <Alert
                message={
                  <>
                    «Реквизировать. Мы реквизируем этот рич контент. Это морской
                    термин» <br /> – Джек Воробей
                  </>
                }
                type="info"
              />

              <div>
                <Form.Item
                  name="url"
                  label="Ссылка на страницу с «реквизируемым» контентом"
                  hasFeedback
                  rules={[
                    { required: true },
                    { type: "url", warningOnly: true },
                    {
                      type: "string",
                      min: 6,
                    },
                  ]}
                >
                  <Input
                    disabled={isLoading}
                    placeholder="Например, https://istyle.cz/macbook-pro-14-...-stribrny.html"
                  />
                </Form.Item>
                <Form.Item
                  name="containerSelector"
                  hasFeedback
                  label="html-cелектор контейнера c контентом (На istyle.cz это обычно .block-static-block)"
                  initialValue=".block-static-block"
                  rules={[{ required: true }, { type: "string" }]}
                >
                  <Input disabled={isLoading} />
                </Form.Item>
              </div>

              {!!errorMessage && <Alert message={errorMessage} type="error" />}

              <Button type="primary" htmlType="submit" loading={isLoading}>
                {!isLoading && `⛵ Поднять паруса!`}
                {isLoading && loadingButtonText}
              </Button>

              {(successMessage || isEnd) && (
                <Space direction="vertical">
                  {!!successMessage && (
                    <Alert message={successMessage} type="success" />
                  )}

                  {!!isEnd && (
                    <>
                      <a
                        rel="noreferrer"
                        href={`https://cdn.iport.ru/rc-pirate/${resultFolderTimestamp}/html/index.html`}
                        target="_blank"
                        style={{ color: `#1677ff` }}
                      >
                        Посмотреть превью (в новой вкладке)
                      </a>
                      <a
                        rel="noreferrer"
                        href={`https://cdn.iport.ru/rc-pirate/${resultFolderTimestamp}/html.zip`}
                        style={{
                          color: `#1677ff`,
                          borderBottom: `1px dashed currentColor`,
                        }}
                        download
                        target="_blank"
                      >
                        Скачать архив
                      </a>
                    </>
                  )}
                </Space>
              )}
            </Space>
          </Form>
        </Card>
      </main>
    </>
  );
}
