import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Card, Space, Alert, Form, Input, Button } from "antd";
import { useState } from "react";

export default function Home() {
  const [isLoading, setIsLoading] = useState<boolean>(false);

  const onSubmit = () => {
    setIsLoading(true);

    setTimeout(() => setIsLoading(false), 1000);
  };

  return (
    <>
      <Head>
        <title>🏴‍☠️ Yo-ho-ho!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Card title="🏴‍☠️ Попутный ветер!" style={{ width: "40rem" }}>
          <Form onFinish={onSubmit} layout="vertical">
            <Space direction="vertical" size={40} style={{ width: "100%" }}>
              <Alert
                message={
                  <>
                    «Реквизировать. Мы реквизируем этот контент. Это морской
                    термин» <br /> – Джек Воробей
                  </>
                }
                type="info"
              />

              <div>
                <Form.Item
                  name="url"
                  label="Ссылка на страницу с «реквизируемым» контентом"
                  hasFeedback
                  rules={[
                    { required: true },
                    { type: "url", warningOnly: true },
                    {
                      type: "string",
                      min: 6,
                    },
                  ]}
                >
                  <Input
                    disabled={isLoading}
                    placeholder="Например, https://istyle.cz/macbook-pro-14-...-stribrny.html"
                  />
                </Form.Item>
                <Form.Item
                  name="container-select"
                  hasFeedback
                  label="html-cелектор контейнера c контентом (На istyle.cz это обычно .block-static-block)"
                  initialValue=".block-static-block"
                  rules={[{ required: true }, { type: "string" }]}
                >
                  <Input disabled={isLoading} />
                </Form.Item>
              </div>

              <Button type="primary" htmlType="submit" loading={isLoading}>
                ⛵ Поднять паруса!
              </Button>
            </Space>
          </Form>
        </Card>
      </main>
    </>
  );
}
